### ISSUE TITLE
About mixtrain in DynaBOA code

### ISSUE THREAD

**Issue by dqj5182** [syguan96/DynaBOA#37]
Good morning,

Just have a question regarding mixtrain argument in DynaBOA code (including lower_level_mixtrain and upper_level_mixtrain).
I have confused with what exactly is mixtrain. According to the code, it seems that it allows the model to do label loss on h3.6m batch extracted from retrieval. However, the paper does not seem to mention mixtrain but mention an ablation study on "Adapting to non-stationary streaming data with highly mixed 3DPW and 3DHP videos.". But here, I am not sure whether the mixtrain procedure really uses 3DHP videos in the code. Could you make this clear on how to understand the mixtrain in the DynaBOA code in relation with the T-PAMI paper?

**Comment by gsygsy96** [comment]
Hi, sorry for the misunderstanding. 
In the code, the flag of 'mix_train' means that both h36m data and test data (e.g., 3DPW) are used to adapt the model (lower level or upper level). 
In the paper, we concatenate 3DPW and 3DHP data to form a new test dataset.

**Comment by dqj5182** [comment]
Ahha I see. Then, as far as I understand, mixtrain is a very general concept of using H3.6M and 3DPW dataset.

Lastly, I just want to ask whether using both H3.6M and 3DHP is also implemented for the final DynaBOA code. May I get clarification for this part?

**Comment by gsygsy96** [comment]
Yes, for all test datasets, we use a subset of h3.6m as a retrieval database.

**Comment by Mirandl** [comment]
Hi, can I make a question about your  cluster files for retrieval from H3.6M?

 I wonder how did you generate the _h36m_random_sample_center_10_10.pt_, and _cluster_res_random_sample_center_10_10_potocol2.pt_.
to what I guess,  it should be to put all the h36m images into the encoder, and use that features to make clusters, without using the regressor, is that right? 

I also wonder how did u match the features clusters with their images, could u show me some code about it?
the reason why I ask this is because I want to reuse this idea and retrain this cluster for other models and need more details, hope you can understand.
thank you!

**Comment by syguan96** [comment]
Hi, please give me an email address,  so that I can send the code to you for reference. But I didn't clean it.

**Comment by Mirandl** [comment]
> Hi, please give me an email address, so that I can send the code to you for reference. But I didn't clean it.

hi, my address is  miranda018@163.com, thank you!
